# Generated by Django 4.1 on 2022-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lapiceras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("punta", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Libros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("autor", models.CharField(max_length=50)),
                ("cant_paginas", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Revistas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=50)),
                ("cant_paginas", models.CharField(max_length=50)),
            ],
        ),
    ]
