# Generated by Django 4.1 on 2022-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Albumes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tematica", models.CharField(max_length=50)),
                ("cant_figuritas_total", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Lapiceras",),
    ]
