# Generated by Django 4.1 on 2022-09-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0002_albumes_delete_lapiceras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revistas", name="año", field=models.IntegerField(),
        ),
    ]
