# Generated by Django 4.1 on 2022-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0003_alter_revistas_año"),
    ]

    operations = [
        migrations.AddField(
            model_name="revistas",
            name="tema",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
    ]
