# Generated by Django 4.1 on 2022-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0004_revistas_tema"),
    ]

    operations = [
        migrations.RemoveField(model_name="revistas", name="año",),
        migrations.AddField(
            model_name="revistas",
            name="anio",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
    ]
