# Generated by Django 4.1 on 2022-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0005_remove_revistas_año_revistas_anio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revistas", name="anio", field=models.IntegerField(),
        ),
    ]
