# Generated by Django 4.1 on 2022-09-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppEditorial", "0006_alter_revistas_anio"),
    ]

    operations = [
        migrations.RemoveField(model_name="revistas", name="anio",),
    ]
